In [1]:
## import necessary packages
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
## import ols 
from statsmodels.formula.api import ols

In [14]:
## import the data
data = pd.read_csv('/Users/geoffpoint-du-jour/Downloads/Forecasting/ECON-522-Forecasting-Project/Climate Data/merged_historical.csv')
# add cpi data to the data frame
cpi_data = pd.read_csv('/Users/geoffpoint-du-jour/Downloads/Forecasting/ECON-522-Forecasting-Project/Climate Data/CPI.csv')
bus_loans = pd.read_csv('/Users/geoffpoint-du-jour/Downloads/Forecasting/ECON-522-Forecasting-Project/Climate Data/BUSLOANS.csv')
data['CPI'] = cpi_data['CPIAUCSL']
data['BUSLOANS'] = bus_loans['BUSLOANS']
data.head()

,DATE,loan_growth,chargeoff_rate,gdp_growth,unemployment_rate,loan_growth_lag1,chargeoff_lag1,CPI,BUSLOANS
0,1986-03-31,1.242338,1.46,0.929415,7.033333,0.954941,1.45,21.48,11.2894
1,1986-06-30,1.192832,1.47,0.449286,7.166667,1.242338,1.46,21.62,11.5179
2,1986-09-30,1.216399,1.56,0.952121,6.966667,1.192832,1.47,22.00,11.7667
3,1986-12-31,4.120364,1.48,0.534959,6.833333,1.216399,1.56,22.00,12.0269
4,1987-03-31,1.634093,1.27,0.739107,6.600000,4.120364,1.48,21.95,12.2788

In [13]:
bus_loans.head()

  observation_date  BUSLOANS
0       1947-01-01   11.2894
1       1947-02-01   11.5179
2       1947-03-01   11.7667
3       1947-04-01   12.0269
4       1947-05-01   12.2788